# Use an official Golang image as the base
FROM golang:alpine

# Set the working directory to /app
WORKDIR /go-practice

# Copy the Go module and dependencies
COPY go.mod go.sum ./

# Install dependencies
RUN go mod tidy

# Copy the application code
COPY . .

# Build the Go application
RUN go build -o go-practice main.go

# Expose the port
EXPOSE 9090

# Define the default command to run when the container starts
CMD ["go-practice"]